### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by townmulti** [AdamBrodzinski/react-meteor-tests#1]
Thanks for this tutorial. I git cloned the gist and followed through the tutorial. I am developing on a virtual server with a domain name not localhost, and I ran meteor with my ROOT URL. The test never loads in the browser but just gives the loading sign under jasmine-client-unit - mirror. I updated meteor. Do you know what I could possibly try to get the tests to run?

**Comment by AdamBrodzinski** [comment]
Hmm, what version is the velocity at ? I've had problems with Jasmine and Velocity running lately :frowning: Actually in my apps i'm using karma outside of Velocity and running it there. Perhaps that would work better with the virtual server?

**Comment by townmulti** [comment]
autopublish             1.0.4  (For prototyping only) Publish the entire database to all clients
blaze-html-templates    1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                   1.0.6  Check whether a value matches a pattern
ejson                   1.0.7  Extended and Extensible JSON library
insecure                1.0.4  (For prototyping only) Allow all database writes from the client
jquery                  1.11.4  Manipulate the DOM using CSS selectors
logging                 1.0.8  Logging facility.
meteor-base             1.0.1  Packages that every Meteor app needs
mobile-experience       1.0.1  Packages for a great mobile user experience
mongo                   1.1.2  Adaptor for using MongoDB and Minimongo over DDP
random                  1.0.4  Random number generator and utilities
react                   0.1.13  Everything you need to use React with Meteor.
reactive-dict           1.1.2  Reactive dictionary
reload                  1.1.4  Reload the page while preserving application state.
sanjo:jasmine           0.20.1  Velocity integration of the Jasmine testing framework
session                 1.1.1  Session variable
spacebars               1.0.7  Handlebars-like template language for Meteor
standard-minifiers      1.0.1  Standard minifiers used with Meteor apps by default.
tracker                 1.0.9  Dependency tracker to allow reactive callbacks
velocity:html-reporter  0.9.0  Reactive Velocity test reports in your app.

is my meteor list.

I tried to drop the karma gist from your article in tests/karma directory. Was there something else I needed to remove or change?

**Comment by AdamBrodzinski** [comment]
You'll likely need to tweak what gets pulled in at the karma config as the dir. structure is prob. a bit different than mine.

**Comment by townmulti** [comment]
Got it to work, but moved it to a Windows localhost to test. Currently only working with sangjo:jasmine 0.14.0 for me though. React testing is cool. Thanks for writing the very helpful article AdamBrodzinski.

**Comment by AdamBrodzinski** [comment]
Glad you got it to work!
